#!/usr/bin/env python3
# Language dictionary extracted from neon.py

TRANSLATIONS_EN = {'language.title': '=== LANGUAGE SELECTION ===',
 'language.subtitle': 'Available codes:',
 'language.option': '- {code} : {name}',
 'language.prompt': 'Language (fr/en/it/es) > ',
 'language.selected': 'Active language: {code} ({name})',
 'language.invalid': 'Invalid code. Use fr, en, it, es.',
 'statusline.compact': 'HP:{hp} EN:{energy} HK:{hack} AL:{alarm} CR:{credits} FR:{fragments}/3',
 'leaderboard.title': '=== LEADERBOARD ===',
 'leaderboard.entry': '#{idx} {line}',
 'leaderboard.none': 'No score recorded.',
 'intro.press_enter': 'Press Enter to start...',
 'startup.launching': 'Launching game...',
 'startup.player_name_prompt': 'Player name: ',
 'startup.player_name_echo': 'Player: {name}',
 'startup.difficulty_title': '=== DIFFICULTY SELECTION ===',
 'startup.difficulty_1': '1. Cyber walk   - Hack: 60s  Combat: 10s  Reflex: 6s  Score multiplier: 1x',
 'startup.difficulty_2': '2. Cyber trial  - Hack: 45s  Combat: 6s   Reflex: 4s  Score multiplier: 2x',
 'startup.difficulty_3': '3. Cyber sweat  - Hack: 30s  Combat: 4s   Reflex: 2s  Score multiplier: 3x',
 'startup.difficulty_4': '4. Cyber violence - Hack: 20s  Combat: 3s   Reflex: 3s  Score multiplier: 4x',
 'startup.difficulty_prompt': 'Choose level (1-4): ',
 'startup.difficulty_invalid': 'Invalid level, difficulty 3 selected by default.',
 'map.title': '=== MAP ===',
 'map.legend': 'Legend: P=Player | C=Core | .=Visited room | E=Enemy | L=Loot | F=Fragment | M=Multi | #=Unknown',
 'describe.enemy_present': '⚠ Enemy present: {enemy}',
 'describe.core_hp': 'CORE Sentinel HP: {hp}',
 'describe.locked': '🔒 Room locked.',
 'describe.terminal': '💻 Terminal detected.',
 'describe.item_visible': '📦 Visible item: {item}',
 'describe.fragment_visible': '🧩 ROM fragment detected: {fragment_id}',
 'describe.core_detected': '===== ☢ CENTRAL CORE detected! =====',
 'move.locked_exit': '🔒 Cannot leave: lockdown active.',
 'move.wall': 'Structural wall.',
 'scan.title': '=== DEEP SCAN ===',
 'scan.cost': 'Scan energy cost: {cost}',
 'scan.object_found': 'Hidden item detected: {item}',
 'scan.lock_pulse': 'Lock pulses at variable frequency.',
 'scan.ports_open': 'Intrusion ports are still open.',
 'scan.rom_signature': 'Fragmented ROM signature detected in this room.',
 'scan.nothing': 'Nothing new detected.',
 'echo.title': '=== EXTENDED ECHO ===',
 'echo.cost': 'Echo energy cost: {cost}',
 'echo.detected': 'Tactical signatures detected around you: {count}',
 'echo.none': 'No tactical signature detected around you.',
 'story.title': '=== DECRYPTED ROM FILE ===',
 'story.id': 'ID: {id}',
 'story.name': 'Title: {title}',
 'story.hacker': 'Hacker: {hacker}',
 'story.context': 'Context: {context}',
 'story.logs': '--- LOGS ---',
 'story.epilogue': '--- EPILOGUE ---',
 'fragments.title': '=== ROM FRAGMENTS ===',
 'fragments.count': 'Collection: {found}/{total}',
 'fragments.line': '[{mark}] {id} - {label}',
 'fragments.unlocked': 'Access to the complete narrative file unlocked.',
 'fragments.read_prompt': 'Read the story now? (y/n) ',
 'fragments.incomplete': 'Collect all 3 fragments to decrypt the full story.',
 'hack.matrix.title': '=== INTRUSION MATRIX ===',
 'hack.matrix.sequence': 'Target sequence: {sequence}',
 'hack.matrix.rules': 'Step 1 free | Step 2 same column | Step 3 same row',
 'hack.matrix.step_prompt': 'Step {step} > ',
 'hack.matrix.timeout': 'Time exceeded',
 'hack.matrix.incorrect': 'Incorrect code',
 'hack.matrix.same_column': 'Same column required',
 'hack.matrix.same_row': 'Same row required',
 'core_hint.east': 'HINT: The core is to the east.',
 'core_hint.west': 'HINT: The core is to the west.',
 'core_hint.south': 'HINT: The core is to the south.',
 'core_hint.north': 'HINT: The core is to the north.',
 'hack.blocked_core': 'The CORE is protected. Neutralize the enemy first.',
 'hack.nothing': 'Nothing to hack here.',
 'hack.title': '=== HACK ===',
 'hack.cost': 'Energy cost: {cost}',
 'hack.alarm_triggered': '⚠ Warning: Alarm level {alarm} triggered!',
 'hack.alarm_enemy': '🚨 Alarm enemy deployed in this room!',
 'hack.reduced': 'Hack reduced to {hack}',
 'hack.standard_success': '💻 Standard hack succeeded. Choose loot:',
 'hack.fragment_ping': '🛰️ Terminal intel: ROM signatures mapped ({count}).',
 'hack.fragment_ping_none': 'Terminal intel: no unknown ROM signatures to reveal.',
 'hack.loot.a': 'A. Credits',
 'hack.loot.b': 'B. Neuro heal (+25 HP)',
 'hack.loot.c': 'C. Hack upgrade (+5 HK)',
 'hack.loot.d': 'D. Cybernetic heal (+10 HP)',
 'hack.loot.prompt': 'Loot > ',
 'hack.loot.heal': '🧠 Heal applied: +25 HP',
 'hack.loot.upgrade': '⚙ Hack upgrade applied: +5 HK',
 'hack.loot.cyber_heal': '⚕️ Cybernetic heal applied: +10 HP',
 'hack.loot.credits': '💰 Credit loot obtained: +{credits}',
 'hack.success.credits': '💻 Hack succeeded! +{credits} credits',
 'hack.alarm_reduced': 'Alarm reduced by 1.',
 'hack.unlock_room': '🔓 Room unlocked.',
 'hack.core_pirated': '☢ CORE hacked. Extraction possible.',
 'hack.done_ms': 'Hack completed in {ms} ms',
 'attack.no_target': 'No target.',
 'attack.stance.aggressive': 'The enemy charges aggressively, ready to hit hard.',
 'attack.stance.defensive': 'The enemy turtles behind solid defenses.',
 'attack.stance.unstable': 'The enemy moves erratically and unpredictably.',
 'attack.prompt': 'Combat: A frontal | B feint | C overload (choose within {time}s)',
 'attack.choice_prompt': 'Choice > ',
 'attack.timeout': 'Reaction too slow: random combat action selected.',
 'attack.reflex_prompt': '⚡ Reflex: type {char} quickly',
 'attack.reflex.success': 'Success in {ms} ms! Bonus: reduced damage.',
 'attack.reflex.failure': 'Failed in {ms} ms! Penalty: increased damage.',
 'attack.bonus.surcharge': 'Overload augment activated: reduced damage!',
 'attack.bonus.force': 'Strength augment activated: reduced damage!',
 'attack.bonus.vitesse': 'Speed augment activated: reduced damage!',
 'attack.core.hit': 'You strike the CORE Sentinel! Damage: {damage}',
 'attack.core.hp': 'CORE Sentinel HP: {hp}',
 'attack.core.counter': 'CORE Sentinel counterattacks! You take {damage} damage.',
 'attack.core.neutralized': 'CORE Sentinel neutralized!',
 'attack.core.remaining_hack': 'Sentinel is down, but you still need to hack the CORE.',
 'attack.neutralize': 'You neutralize {enemy}',
 'attack.taken': 'You take {damage} damage',
 'enemy_attack.core': '⚠️ CORE Sentinel attacks you! You take {damage} damage.',
 'enemy_attack.normal': '⚠️ {enemy} attacks you! You take {damage} damage.',
 'take.fragment': 'ROM fragment recovered: {fragment_id} ({count}/3)',
 'take.item': 'Taken: {item}',
 'take.none': 'Nothing to take.',
 'use.absent': 'Item not found.',
 'use.used': '{item} used.',
 'inventory.title': 'Inventory:',
 'inventory.empty': 'Empty',
 'inventory.medkit': '- medkit: restores 25 HP',
 'inventory.energy_cell': '- energy_cell: restores 25 energy',
 'inventory.exploit_chip': '- exploit_chip: +10 hack',
 'status.title': '=== AUGMENTED GEAR ===',
 'status.synaptique': '- Synaptic augment: +10s hack time',
 'status.surcharge': '- Overload augment: improves overload in combat',
 'status.interface': '- Enhanced hacker neural interface: matrix reduced by 1',
 'status.combat_chip': '- Combat chip: doubles action time in combat',
 'status.force': '- Strength augment: improves frontal attack',
 'status.vitesse': '- Speed augment: improves feint',
 'status.dissipateur': '- Energy dissipator: halves action energy costs',
 'status.none': 'None',
 'status.characteristics': '=== CHARACTERISTICS ===',
 'status.line': 'HP (Heal Points):{hp} EN (Energy):{energy} HK (Hack):{hack} AL (Alarm):{alarm} CR (Credits):{credits}',
 'status.fragments': 'ROM fragments: {count}/3',
 'help.commands': 'Commands: n s e w | scan/sc | echo/ec | hack/h | attack/at | take/t | use/u <item> | inventory/inv '
                  '| map/m | status/stat | fragments/fra | shop/sh | help/he | quit/q',
 'shop.title': '=== SHOP ===',
 'shop.credits': 'Available credits: {credits}',
 'shop.items': 'Available items:',
 'shop.item.1': '1. Synaptic augment - 100 credits: +10s hack time',
 'shop.item.2': '2. Overload augment - 100 credits: improves overload in combat',
 'shop.item.3': '3. Enhanced neural hacker interface - 150 credits: matrix reduced by 1',
 'shop.item.4': '4. Combat chip - 150 credits: doubles action time in combat',
 'shop.item.5': '5. Strength augment - 100 credits: improves frontal attack',
 'shop.item.6': '6. Speed augment - 100 credits: improves feint',
 'shop.item.7': '7. Energy dissipator - 300 credits: halves EN costs for actions',
 'shop.item.0': '0. Exit',
 'shop.prompt': 'Choice > ',
 'shop.buy.1': 'Synaptic augment purchased! +10s hack time.',
 'shop.buy.2': 'Overload augment purchased! Overload improved in combat.',
 'shop.buy.3': 'Neural interface purchased! Matrix reduced by 1.',
 'shop.buy.4': 'Combat chip purchased! Combat time doubled.',
 'shop.buy.5': 'Strength augment purchased! Frontal attack improved.',
 'shop.buy.6': 'Speed augment purchased! Feint improved.',
 'shop.buy.7': 'Energy dissipator purchased! Action EN costs are now halved.',
 'shop.invalid': 'Invalid choice or insufficient credits.',
 'enemy_turn.reinforcement': '⚠ System reinforcement detected',
 'score.title': '=== FINAL SCORE ===',
 'score.base': 'Base score: {score}',
 'score.rom_bonus': 'ROM fragment bonus: {bonus}',
 'score.time_bonus': 'Total time bonus: {bonus}',
 'score.hack_bonus': 'Hack time bonus: {bonus}',
 'score.rank': 'Your score ranks you #{rank}.',
 'core.pirated': '=== CORE HACKED ===',
 'main.spawn': 'spawn position {x},{y}',
 'main.core': 'core position {x},{y}',
 'main.story_channel': 'ROM channel detected: file {story_id} split into 3 caches.',
 'main.death': 'You collapse into the network.',
 'main.alarm_game_over': '🚨 Maximum alarm reached! Game over.',
 'ui.choice_prompt': 'Choice > ',
 'ui.reflex_input_prompt': '> ',
 'ui.command_prompt': '\n> ',
 'ui.quit_confirm': 'Do you want to quit the current run? (y/n) ',
 'ui.replay_prompt': 'Play again? (y/n) ',
 'ui.unknown_command': 'Unknown command.',
 'error.unhandled': 'An error occurred: {error}',
 'intro.full': '\n'
               '==============================\n'
               '    NEON NODE v6\n'
               '==============================\n'
               '\n'
               'Infiltrate the megastructure.\n'
               'Reach the central CORE, hack it, and get out alive.\n'
               '\n'
               'For hacks:\n'
               '- The higher your hack, the smaller the matrix.\n'
               '- Step 1: freely find the correct hex value in the matrix (must match the first requested code '
               'value).\n'
               '- Step 2: must be in the same column as step 1.\n'
               '- Step 3: must be in the same row as step 2.\n'
               '\n'
               'Time is limited to complete the hack, and failure raises your alarm and lowers your hack.\n'
               '\n'
               'Credits are earned by hacking terminals and can be used to buy upgrades in the shop.\n'
               'The faster you hack, the more credits you earn!\n'
               '\n'
               'Commands:\n'
               ' north / n : move north\n'
               ' south / s : move south\n'
               ' east / e : move east\n'
               ' west / w  : move west\n'
               ' scan / sc : scan the room for hidden objects or clues\n'
               ' echo / ec : probe nearby rooms and reveal tactical map markers\n'
               ' hack / h : try to hack a terminal or disable a lock\n'
               ' attack : engage combat against a present enemy\n'
               ' take / t : pick up a visible item in the room or found by scan\n'
               ' use <item> / u <item> : use an inventory item (e.g. use medkit)\n'
               ' map / m : display the level map (P = position, C = core, . = visited room, # = unvisited room)\n'
               ' inventory / inv : display inventory\n'
               ' status / stat : display status and upgrades\n'
               ' fragments / fra : display collected ROM fragments and the story file\n'
               ' shop / sh : open the shop to buy upgrades with credits\n'
               ' help / he : display commands\n'
               ' quit / q : quit the game\n',
 'content.rom_story_archive': [{'id': 'ROM-AX13',
                                'title': 'AX13 // Last Drift',
                                'hacker': 'Mara Voss (she)',
                                'bio': 'Former network engineer at Kheiron Dynamics, disappeared after trying to leak '
                                       'internal code.',
                                'fragments': [{'id': 'AX13-1', 'label': 'Bunker Bootlog'},
                                              {'id': 'AX13-2', 'label': 'Progress Log'},
                                              {'id': 'AX13-3', 'label': 'End Signal'}],
                                'logs': ['[2091-04-12 22:13] Infiltration at level C entrance. Drone noise louder than '
                                         'expected.',
                                         '[2091-04-12 22:17] The airlock still smells like ozone. I designed this '
                                         'protocol six years ago. Seeing it reused here makes me sick.',
                                         '[2091-04-12 22:24] A camera tracked me without triggering an alert. Either I '
                                         'am already flagged, or someone is slowing the system.',
                                         '[2091-04-12 22:31] Thermal lock neutralized. I lost 30% of my tools.',
                                         '[2091-04-12 22:38] Lian always said we end up living inside the structures '
                                         'we hate. I think she was right.',
                                         '[2091-04-12 22:49] I saw the Sentinel in the distance. It is not a standard '
                                         'bot. It hesitates before turning its optics toward me.',
                                         '[2091-04-12 23:02] Cascading alarms. Corridors keep reconfiguring in loops.',
                                         '[2091-04-12 23:05] Paradox: I came in to sabotage this system, yet every '
                                         'opened door proves my old code still holds better than I do.',
                                         '[2091-04-12 23:09] If anyone reads this: never stay still after a successful '
                                         'hack.',
                                         '[2091-04-12 23:11] I am bleeding into my suit. Leaving this file in three '
                                         'ROM caches.'],
                                'epilogue': "End of transmission. Mara's signal cuts abruptly after a security "
                                            'overload.'},
                               {'id': 'ROM-KR22',
                                'title': 'KR22 // Red Debt',
                                'hacker': 'Kenji Rault (he)',
                                'bio': 'Independent data courier, infiltrated the megastructure to erase a debt '
                                       'contract.',
                                'fragments': [{'id': 'KR22-1', 'label': 'Night Warrant'},
                                              {'id': 'KR22-2', 'label': 'Corrupted Map'},
                                              {'id': 'KR22-3', 'label': 'Last Pledge'}],
                                'logs': ['[2088-09-03 01:40] Silent entry. Paid a fixer for a single-use key.',
                                         '[2088-09-03 01:46] I run better when I am angry. Bad news: I have been angry '
                                         'for years.',
                                         '[2088-09-03 02:02] My scanner lies. Some rooms exist, then vanish.',
                                         '[2088-09-03 02:09] My sister thinks I still carry anonymous packages. I '
                                         'never told her those packages are sometimes evidence.',
                                         '[2088-09-03 02:19] I got credits, but every terminal raises the pressure.',
                                         '[2088-09-03 02:25] The CORE broadcasts my old medical record. They know me.',
                                         '[2088-09-03 02:28] Stupid paradox: stealing credits to erase debt still '
                                         'obeys the logic of accounting.',
                                         '[2088-09-03 02:33] I keep going. If I get out, my sister can finally sleep '
                                         'debt-free.',
                                         '[2088-09-03 02:36] Impact. Drone in my blind spot. Splitting this log into 3 '
                                         'ROM fragments.'],
                                'epilogue': 'The debt contract was never found in public archives.'},
                               {'id': 'ROM-NQ05',
                                'title': 'NQ05 // Cold Chamber',
                                'hacker': 'Noor Qassem (they)',
                                'bio': 'Freelance cryptanalyst specialized in dead memory systems and heritage AIs.',
                                'fragments': [{'id': 'NQ05-1', 'label': 'Approach Trace'},
                                              {'id': 'NQ05-2', 'label': 'Interface Rupture'},
                                              {'id': 'NQ05-3', 'label': 'Core Voice'}],
                                'logs': ['[2093-02-20 18:05] The walls are cold. Everything here consumes heat like '
                                         'evidence.',
                                         '[2093-02-20 18:11] A door replayed my own breathing three seconds ahead.',
                                         '[2093-02-20 18:27] One room returned my reflection with a 4-second lead.',
                                         '[2093-02-20 18:36] In the server squat we used to say one saved archive can '
                                         'be worth a riot.',
                                         '[2093-02-20 18:51] Sentinel routines imitate human errors. Bad sign.',
                                         '[2093-02-20 19:04] I landed a clean hack. Alarm still climbed.',
                                         '[2093-02-20 19:10] Paradox: I preserve memory fragments while I am no longer '
                                         'sure some memories are mine.',
                                         '[2093-02-20 19:18] If I fall, someone get these logs out. Let it serve '
                                         'something else.',
                                         '[2093-02-20 19:21] Contact lost. Locking my story into ROM fragments.'],
                                'epilogue': "Noor's remaining data is flagged as irreconcilable."},
                               {'id': 'ROM-LV77',
                                'title': 'LV77 // Wild Fork',
                                'hacker': 'Leia Varek (she)',
                                'bio': 'Developer from a free-software collective dissolved after a raid.',
                                'fragments': [{'id': 'LV77-1', 'label': 'Hidden Repo'},
                                              {'id': 'LV77-2', 'label': 'Branch Conflict'},
                                              {'id': 'LV77-3', 'label': 'Final Commit'}],
                                'logs': ['[2090-06-03 00:11] Entry validated. Scanners run on an old Unix base with '
                                         'fresh paint.',
                                         '[2090-06-03 00:19] Ada used to say a fork is sometimes a breakup written in '
                                         'clean syntax.',
                                         '[2090-06-03 00:28] I came in to steal a repository that already belonged to '
                                         'me before patenting.',
                                         '[2090-06-03 00:42] First Sentinel neutralized.',
                                         '[2090-06-03 00:57] Paradox: I hate monopolies, yet I still hope my code '
                                         'survives under their logo.',
                                         '[2090-06-03 01:03] If anyone reads this: publishing can be more dangerous '
                                         'than deleting.'],
                                'epilogue': 'The repository was never republished in full.'},
                               {'id': 'ROM-SM04',
                                'title': 'SM04 // Silent Zone',
                                'hacker': 'Sam Mirek (he)',
                                'bio': 'Former pirate radio technician specialized in underground broadcasts.',
                                'fragments': [{'id': 'SM04-1', 'label': 'Frequency 1'},
                                              {'id': 'SM04-2', 'label': 'Frequency 2'},
                                              {'id': 'SM04-3', 'label': 'Frequency 3'}],
                                'logs': ['[2087-11-19 03:10] I recognize electric noise before I even spot drones.',
                                         '[2087-11-19 03:21] A wall speaker replayed my own pirate broadcast from '
                                         '2084.',
                                         '[2087-11-19 03:34] My brother used to say speaking too loud always attracts '
                                         'boots.',
                                         '[2087-11-19 03:41] Paradox: I hack frequencies to free speech, but here '
                                         'every word pins my location.',
                                         '[2087-11-19 03:52] If I fall, let the noise keep circulating.'],
                                'epilogue': "No source confirmed Sam's extraction."},
                               {'id': 'ROM-IR31',
                                'title': 'IR31 // Administrative Ash',
                                'hacker': 'Iris Ren (she)',
                                'bio': 'Former administrative employee who sabotaged automated evictions.',
                                'fragments': [{'id': 'IR31-1', 'label': 'Fake File'},
                                              {'id': 'IR31-2', 'label': 'Inverted Procedure'},
                                              {'id': 'IR31-3', 'label': 'Ash Archive'}],
                                'logs': ['[2092-01-08 19:14] I still know the internal menus better than the agents '
                                         'who enforce them.',
                                         '[2092-01-08 19:25] I already saved one hundred and thirty-two files with '
                                         'deliberate typos.',
                                         '[2092-01-08 19:39] Here, terminals classify lives like tickets.',
                                         '[2092-01-08 19:48] Paradox: forging data to restore a bit of justice is '
                                         'still forging.',
                                         '[2092-01-08 19:56] I keep going.'],
                                'epilogue': 'Internal logs mention a persistent human anomaly.'},
                               {'id': 'ROM-DX90',
                                'title': 'DX90 // Dissident Syntax',
                                'hacker': 'Dax Oren (they)',
                                'bio': 'Maintainer of an encrypted underground distribution.',
                                'fragments': [{'id': 'DX90-1', 'label': 'Bootstrap'},
                                              {'id': 'DX90-2', 'label': 'Kernel Drift'},
                                              {'id': 'DX90-3', 'label': 'Root Panic'}],
                                'logs': ['[2094-07-01 21:03] Key injected into the secondary network.',
                                         '[2094-07-01 21:17] Collective meeting yesterday: two hours debating a '
                                         'package name.',
                                         '[2094-07-01 21:31] Paradox: we want to abolish hierarchies, yet someone '
                                         'always ends up merging alone.',
                                         '[2094-07-01 21:44] First shot dodged.',
                                         '[2094-07-01 21:52] Even revolutions need someone to remind you to eat.'],
                                'epilogue': 'A similar key reappeared later across several free networks.'},
                               {'id': 'ROM-PT12',
                                'title': 'PT12 // Ghost Line',
                                'hacker': 'Pia Torres (she)',
                                'bio': 'Former autonomous metro driver turned technical saboteur.',
                                'fragments': [{'id': 'PT12-1', 'label': 'Dead Rail'},
                                              {'id': 'PT12-2', 'label': 'Bypass'},
                                              {'id': 'PT12-3', 'label': 'Last Line'}],
                                'logs': ['[2089-12-14 04:05] The silence here sounds like tunnels before power '
                                         'returns.',
                                         '[2089-12-14 04:18] I learned to slow systems before I learned to break them.',
                                         '[2089-12-14 04:29] Paradox: I hate automation, yet I trust my reflexes more '
                                         'than people.',
                                         '[2089-12-14 04:37] Two drones behind me.'],
                                'epilogue': 'The privatized transport file never resurfaced.'},
                               {'id': 'ROM-HQ44',
                                'title': 'HQ44 // Noise Archive',
                                'hacker': 'Hugo Quent (he)',
                                'bio': 'Noise musician turned signal pirate.',
                                'fragments': [{'id': 'HQ44-1', 'label': 'Impulse'},
                                              {'id': 'HQ44-2', 'label': 'Feedback'},
                                              {'id': 'HQ44-3', 'label': 'Cut'}],
                                'logs': ['[2086-03-03 02:14] Every alarm here has almost an exploitable tone.',
                                         '[2086-03-03 02:27] I count my steps like measures.',
                                         '[2086-03-03 02:39] Paradox: turning fear into rhythm does not erase it.',
                                         '[2086-03-03 02:45] I think I hear breathing behind the relays.'],
                                'epilogue': 'An audio extract attributed to Hugo still circulates on pirate networks.'},
                               {'id': 'ROM-ZE08',
                                'title': 'ZE08 // Incomplete Commune',
                                'hacker': 'Zea Elin (she)',
                                'bio': 'Member of a self-managed urban micro-commune.',
                                'fragments': [{'id': 'ZE08-1', 'label': 'Collective Kitchen'},
                                              {'id': 'ZE08-2', 'label': 'Black Meter'},
                                              {'id': 'ZE08-3', 'label': 'Incomplete Exit'}],
                                'logs': ['[2095-05-10 23:01] We shared soup before I left.',
                                         '[2095-05-10 23:14] Energy readings lie exactly like prefects do.',
                                         '[2095-05-10 23:28] Paradox: living without a boss sometimes demands more '
                                         'discipline than the opposite.',
                                         '[2095-05-10 23:37] If I come back, I still have to repair the rooftop solar '
                                         'charger.'],
                                'epilogue': "Zea's district suffered a total blackout two weeks later."}],
 'content.room_descriptions': ['Corridor saturated with red neon.',
                               'Server room humming with thermal relays.',
                               'Abandoned technical zone covered in cables.',
                               'Old security checkpoint.',
                               'Narrow passage with a flickering broken sign.',
                               'Room flooded with intermittent electrical noise.',
                               'Control room with failing holographic displays.',
                               'Ventilation tunnel full of rusted ducts.',
                               'Abandoned lab with strange medical equipment.',
                               'Empty hangar echoing with distant sounds.',
                               'Executive office with destroyed high-tech furniture.',
                               'Storage zone stacked with data crates.',
                               'Meeting room with a broken interactive table.',
                               'Access corridor to blocked elevators.',
                               'Maintenance zone with scattered tools.'],
 'content.enemies': ['Drone', 'Guard', 'Sentry Bot', 'Proxy Hunter'],
 'content.items': ['medkit', 'energy_cell', 'exploit_chip']}
